
ARG REACT_APP_API_URL='http://localhost:4000'
ARG REACT_APP_DOMAINS=[\"domain.com\"]

FROM node:alpine@sha256:c61b6b12a3c96373673cd52d7ecee2314e82bca5d541eecf0bc6aee870c8c6f7 AS yarn_base_image

FROM yarn_base_image AS mailserver_image
COPY mailserver/yarn.lock /React-TrashMail/mailserver/yarn.lock
COPY mailserver/package.json /React-TrashMail/mailserver/package.json
WORKDIR /React-TrashMail/mailserver
RUN yarn install
COPY mailserver /React-TrashMail/mailserver


FROM yarn_base_image AS react_image

COPY react/yarn.lock /React-TrashMail/react/yarn.lock
COPY react/package.json /React-TrashMail/react/package.json
WORKDIR /React-TrashMail/react
RUN yarn install

ARG REACT_APP_API_URL
ARG REACT_APP_DOMAINS

RUN echo ${REACT_APP_API_URL}
RUN echo ${REACT_APP_DOMAINS}

ENV REACT_APP_API_URL=${REACT_APP_API_URL}
ENV REACT_APP_DOMAINS=${REACT_APP_DOMAINS}

COPY react /React-TrashMail/react
RUN yarn build


# Start with the official MongoDB image
FROM mailserver_image

# Copy in mailserver dependencies
COPY --from=react_image /React-TrashMail/react/build /React-TrashMail/mailserver/build

# Define mountable volume
VOLUME ["/React-TrashMail/mailserver/attachments"]

EXPOSE 4000
EXPOSE 25

# Set the command to start the application using the startup script
CMD [ "yarn", "start:docker"]
